name: build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run hadolint/hadolint < Dockerfile
  build:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: koenighotze/github-auschecker
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 110 # Berlin
          format: "YYYY-MM-DD-HH-mm-ss"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: koenighotze # ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            NAME=koenighotze/auschecker
            DESCRIPTION=Simple tool for checking out repos
            VERSION=1.1
            COMMIT_SHA=${{ github.sha }}
            BUILD_TIMESTAMP=${{ steps.time.outputs.time }}
            VCS_URL=${{ github.repository }}
