name: Build

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@0.3.0
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.9.1
        with:
          scan-type: "fs"
          ignore-unfixed: false
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"

  qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          verbose: true
      - name: Check shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
          scandir: '.'

  build-container:
    needs:
      - qa
      - security-scan-code

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          # tags: foo,bar
          # build-args: foo,bar
          # labels: |
          #   foo
          #   bar
